### ISSUE TITLE
Question about removed_docs argument to query

### ISSUE THREAD

**Issue by tmpfs** [quantleaf/probly-search#10]
Thanks for the library, I spent quite a bit of time researching the available libraries for my project and this one strikes the perfect balance for my needs, in particular the support for webassembly is critical!

It seems that if I vacuum the index then there is no need to pass `removed_docs` as the last argument to `query`?

Am i right in thinking that the `removed_docs` argument exists to support the case when documents have been removed but not yet vacuumed from the index and the query should ignore them?

**Comment by marcus-pousette** [comment]
Thanks for your question! Great that you find it useful! 

You have understood it correctly. You only need to pass it if you have not vacuumed the index. The reason for this is that vacuum is a scanning operation, while passing the removed_docs HashSet acts like a filter. An easy condition for vacuuming could be to do it when the ```removed_docs``` set has grown too large. Or do it every X minute (depends on your use case)

**Comment by tmpfs** [comment]
Thanks for the prompt reply, much appreciated 🙏
