### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by tmpfs** [quantleaf/probly-search#22]
Hi @marcus-pousette, hope you are doing well 🙏 

I have been using the 2.0.0-alpha.1 in production for a while now and it's working well. Could we formalize a v2 release please?

But first we need to update some dependencies which have broken the docs.rs build due to updates to nightly. In particular `hashbrown` which depends on `ahash@0.7.7`is causing the problem, see this issue for more info:

https://github.com/tkaitchuck/aHash/issues/200

If I submit a PR to update dependencies could you please merge and publish a new version.

If you want to see your code running [try our app](https://saveoursecrets.com/).

**Comment by marcus-pousette** [comment]
Hey! 
Im doing well thanks, hope you are good too !

Yes, that sounds good!

Cool will check it out 😄

**Comment by tmpfs** [comment]
All good here thanks 😁 

I have updated hashbrown and changed the major version in [this PR](https://github.com/quantleaf/probly-search/pull/23).

If you could land that and publish a new version it would be appreciated 🙏
